################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_TNTDB "tntdb")
    if (NOT PC_TNTDB_FOUND)
        pkg_check_modules(PC_TNTDB "tntdb")
    endif (NOT PC_TNTDB_FOUND)
    if (PC_TNTDB_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_TNTDB_CFLAGS} ${PC_TNTDB_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_TNTDB_INCLUDE_HINTS ${PC_TNTDB_INCLUDE_DIRS} ${PC_TNTDB_INCLUDE_DIRS}/*)
        set(PC_TNTDB_LIBRARY_HINTS ${PC_TNTDB_LIBRARY_DIRS} ${PC_TNTDB_LIBRARY_DIRS}/*)
    endif(PC_TNTDB_FOUND)
endif (NOT MSVC)

find_path (
    TNTDB_INCLUDE_DIRS
    NAMES tntdb.h
    HINTS ${PC_TNTDB_INCLUDE_HINTS}
)

find_library (
    TNTDB_LIBRARIES
    NAMES tntdb
    HINTS ${PC_TNTDB_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    TNTDB
    REQUIRED_VARS TNTDB_LIBRARIES TNTDB_INCLUDE_DIRS
)
mark_as_advanced(
    TNTDB_FOUND
    TNTDB_LIBRARIES TNTDB_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
