################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_BIOSPROTO "libbiosproto")
    if (NOT PC_BIOSPROTO_FOUND)
        pkg_check_modules(PC_BIOSPROTO "libbiosproto")
    endif (NOT PC_BIOSPROTO_FOUND)
    if (PC_BIOSPROTO_FOUND)
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_BIOSPROTO_INCLUDE_HINTS ${PC_BIOSPROTO_INCLUDE_DIRS} ${PC_BIOSPROTO_INCLUDE_DIRS}/*)
        set(PC_BIOSPROTO_LIBRARY_HINTS ${PC_BIOSPROTO_LIBRARY_DIRS} ${PC_BIOSPROTO_LIBRARY_DIRS}/*)
    endif(PC_BIOSPROTO_FOUND)
endif (NOT MSVC)

find_path (
    BIOSPROTO_INCLUDE_DIRS
    NAMES biosproto.h
    HINTS ${PC_BIOSPROTO_INCLUDE_HINTS}
)

find_library (
    BIOSPROTO_LIBRARIES
    NAMES biosproto
    HINTS ${PC_BIOSPROTO_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    BIOSPROTO
    REQUIRED_VARS BIOSPROTO_LIBRARIES BIOSPROTO_INCLUDE_DIRS
)
mark_as_advanced(
    BIOSPROTO_FOUND
    BIOSPROTO_LIBRARIES BIOSPROTO_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
