################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_CXXTOOLS "cxxtools")
    if (NOT PC_CXXTOOLS_FOUND)
        pkg_check_modules(PC_CXXTOOLS "cxxtools")
    endif (NOT PC_CXXTOOLS_FOUND)
    if (PC_CXXTOOLS_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_CXXTOOLS_CFLAGS} ${PC_CXXTOOLS_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_CXXTOOLS_INCLUDE_HINTS ${PC_CXXTOOLS_INCLUDE_DIRS} ${PC_CXXTOOLS_INCLUDE_DIRS}/*)
        set(PC_CXXTOOLS_LIBRARY_HINTS ${PC_CXXTOOLS_LIBRARY_DIRS} ${PC_CXXTOOLS_LIBRARY_DIRS}/*)
    endif(PC_CXXTOOLS_FOUND)
endif (NOT MSVC)

find_path (
    CXXTOOLS_INCLUDE_DIRS
    NAMES cxxtools/allocator.h
    HINTS ${PC_CXXTOOLS_INCLUDE_HINTS}
)

find_library (
    CXXTOOLS_LIBRARIES
    NAMES cxxtools
    HINTS ${PC_CXXTOOLS_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    CXXTOOLS
    REQUIRED_VARS CXXTOOLS_LIBRARIES CXXTOOLS_INCLUDE_DIRS
)
mark_as_advanced(
    CXXTOOLS_FOUND
    CXXTOOLS_LIBRARIES CXXTOOLS_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
